### ISSUE TITLE
Traefik route config file disappears from (doesn't appear in the first place on) traefik filesystem

### ISSUE THREAD

**Issue by sed-i** [canonical/traefik-k8s-operator#111]
### Bug Description

I deployed the load test with the "grafana workaround"
```
sudo -u ubuntu juju remove-relation grafana:ingress traefik
sleep 30
sudo -u ubuntu juju relate grafana:ingress traefik
```
after which grafana was reachable via ingress address.

After about 6 hours of operation, something went wrong (see logs section below), seems like all charms restarted, and grafana became unreachable.

Traefik still had grafana details in relation data,
```bash
$ juju show-unit traefik/0
```
```yaml
  - relation-id: 27
    endpoint: traefik-route
    related-endpoint: ingress
    application-data:
      config: |
        http:
          routers:
            juju-cos-lite-load-test-grafana-router:
              entryPoints:
              - web
              rule: PathPrefix(`/cos-lite-load-test-grafana`)
              service: juju-cos-lite-load-test-grafana-service
          services:
            juju-cos-lite-load-test-grafana-service:
              loadBalancer:
                servers:
                - url: http://grafana-0.grafana-endpoints.cos-lite-load-test.svc.cluster.local:3000/
```

But the config file is not on the filesystem (and curling the grafana endpoint gives 404):
```
ubuntu@pd-ssd-4cpu-8gb:~$ juju ssh --container traefik traefik/0 ls /opt/traefik/juju
juju_ingress_ingress-per-unit_4_prometheus.yaml
juju_ingress_ingress-per-unit_5_loki.yaml
juju_ingress_ingress_20_catalogue.yaml
juju_ingress_ingress_7_alertmanager.yaml
```
After re-relating `grafana:ingress traefik` the file re-appears:
```
ubuntu@pd-ssd-4cpu-8gb:~$ juju ssh --container traefik traefik/0 ls /opt/traefik/juju
juju_ingress_ingress-per-unit_4_prometheus.yaml
juju_ingress_ingress-per-unit_5_loki.yaml
juju_ingress_ingress_20_catalogue.yaml
juju_ingress_ingress_7_alertmanager.yaml
juju_ingress_traefik-route_28_grafana.yaml
```

### To Reproduce

Deploy the bundle (same thing happens on startup).

### Environment

Bundle from edge.

### Relevant log output

```shell
unit-grafana-0: 2022-12-08 01:02:25 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: write tcp 10.1.79.222:43324->10.152.183.132:17070: i/o timeout: write tcp 10.1.79.222:43324->10.152.183.132:17070: i/o timeout
unit-grafana-0: 2022-12-08 01:02:48 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: api connection broken unexpectedly

unit-traefik-0: 2022-12-08 01:05:02 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: [40652e] "unit-traefik-0" cannot open api: try was stopped

unit-grafana-0: 2022-12-08 01:05:14 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: [40652e] "unit-grafana-0" cannot open api: cannot resolve "controller-service.controller-uk8s.svc.cluster.local": lookup controller-service.controller-uk8s.svc.cluster.local: i/o timeout

unit-grafana-0: 2022-12-08 01:05:32 WARNING juju.worker.proxyupdater unable to set snap core settings [proxy.http= proxy.https= proxy.store=]: exec: "snap": executable file not found in $PATH, output: ""

unit-traefik-0: 2022-12-08 01:05:35 WARNING juju.worker.proxyupdater unable to set snap core settings [proxy.http= proxy.https= proxy.store=]: exec: "snap": executable file not found in $PATH, output: ""

unit-traefik-0: 2022-12-08 01:05:46 WARNING juju.worker.uniter.context could not retrieve the cloud API version: unable to determine legacy status for namespace cos-lite-load-test: Get "https://10.152.183.1:443/api/v1/namespaces/cos-lite-load-test": net/http: TLS handshake timeout
unit-grafana-0: 2022-12-08 01:05:46 WARNING juju.worker.uniter.context could not retrieve the cloud API version: unable to determine legacy status for namespace cos-lite-load-test: Get "https://10.152.183.1:443/api/v1/namespaces/cos-lite-load-test": net/http: TLS handshake timeout

unit-grafana-0: 2022-12-08 01:05:59 INFO unit.grafana/0.juju-log Running legacy hooks/start.
unit-traefik-0: 2022-12-08 01:05:59 INFO unit.traefik/0.juju-log Running legacy hooks/start.
```
