### ISSUE TITLE
HTTP to HTTPS redirect

### ISSUE THREAD

**Issue by nsklikas** [canonical/traefik-k8s-operator#177]
### Enhancement Proposal

After tls is enabled in traefik, a rule could be created for HTTP to HTTPS redirects. I see no reason not to do that.

An example of how to implement that can be found [here](https://jensknipper.de/blog/traefik-http-to-https-redirect/).

**Comment by rbarry82** [comment]
Duplicate of #176

**Comment by sed-i** [comment]
From the docs, there are two places to declare https redirect:
- "Traefik global", under entrypoints ([ref](https://doc.traefik.io/traefik/routing/entrypoints/#redirection)). That is the topic of this issue and is not impl'd in the charm.
- Per-service, under middlewares ([ref](https://doc.traefik.io/traefik/middlewares/http/redirectscheme/)). This was impl'd in #178 but we don't really make use of it in practice.

> what I want is that http requests are redirected to the https URL (of traefik). This should not be affected from the proxied application. 
> 
> What is currently implemented is that IF the incoming request scheme is different from the application's scheme, THEN that request is redirected (changes the scheme). This means that http will be redirected to https only if the proxied application is serving https.
>
> -- @nsklikas

**Comment by sed-i** [comment]
More details:

When traefik is related to ca and then curl an ingress url with "http", then the endpoint cannot be reached:
```
$ curl -k http://10.43.8.206/bndl-prometheus-0/api/v1/targets
Moved Permanently%
$ curl -k -L http://10.43.8.206/bndl-prometheus-0/api/v1/targets
404 page not found
```

**Comment by PietroPasotti** [comment]
adding 
```
  address: :80             
  http:                    
    redirections:          
      entryPoint:          
        to: websecure      
        scheme: https      
websecure:                 

``` 

to the static config turns 404 into an internal server error, investigating...
