### ISSUE TITLE
404 when curling proxied https endpoint

### ISSUE THREAD

**Issue by sed-i** [canonical/traefik-k8s-operator#216]
### Bug Description

@mateoflorido reported that curling [kubernetes-dashboard-operator](https://github.com/charmed-kubernetes/kubernetes-dashboard-operator/tree/m/ingress) gives a 404:

```
➜  kubernetes-dashboard-operator git:(m/ingress) curl --insecure https://10.64.140.43/dashboard-kubernetes-dashboard
404 page not found
```

### To Reproduce

Pack [kubernetes-dashboard-operator](https://github.com/charmed-kubernetes/kubernetes-dashboard-operator/tree/m/ingress) and deploy the following bundle:

```yaml
---
bundle: kubernetes
applications:
  kubernetes-dashboard:
    charm: ./kubernetes-dashboard_ubuntu-22.04-amd64.charm
    scale: 1
    constraints: arch=amd64
    trust: true
    resources:
      dashboard-image: rocks.canonical.com/cdk/kubernetesui/dashboard:v2.7.0
      scraper-image: rocks.canonical.com/cdk/kubernetesui/metrics-scraper:v1.0.8
  self-signed-certificates:
    charm: self-signed-certificates
    channel: edge
    revision: 15
    scale: 1
    constraints: arch=amd64
  traefik-k8s:
    charm: traefik-k8s
    channel: edge
    revision: 140
    series: focal
    resources:
      traefik-image: 131
    scale: 1
    constraints: arch=amd64
    storage:
      configurations: kubernetes,1,1024M
    trust: true
relations:
- - traefik-k8s:certificates
  - self-signed-certificates:certificates
- - kubernetes-dashboard:certificates
  - self-signed-certificates:certificates
- - kubernetes-dashboard:ingress
  - traefik-k8s:ingress
```

### Environment

latest/edge, juju 3.2.0.

### Relevant log output

```shell
$ juju deploy --trust ./mateo.yaml

$ juju run traefik-k8s/0 show-proxied-endpoints
proxied-endpoints: '{"kubernetes-dashboard": {"url": "https://10.43.8.219/karma-kubernetes-dashboard"}}'

$ kubectl -n karma logs pod/traefik-k8s-0 -c traefik
[traefik] time="2023-08-03T16:43:57Z" level=debug msg="Adding certificate for domain(s) 10-43-8-219.kubernetes.default.svc.cluster.local,traefik-k8s-0.traefik-k8s-endpoints.karma.svc.cluster.local,traefik-k8s/0"

root@traefik-k8s-0:/var/lib/juju# openssl s_client -showcerts -connect kubernetes-dashboard.karma.svc.cluster.local:443 </dev/null | openssl x509 -text
# --snip--
        Issuer: C = US, CN = self-signed-certificates-operator
# --snip--
        X509v3 extensions:
            X509v3 Subject Alternative Name: 
                IP Address:10.152.183.77, DNS:kubernetes-dashboard.karma.svc, DNS:kubernetes-dashboard.karma.svc.cluster.local, DNS:kubernetes-dashboard.karma, IP Address:10.1.166.111

root@traefik-k8s-0:/# openssl s_client -showcerts -connect localhost:80 </dev/null | openssl x509 -text
# --snip---
        Issuer: CN = TRAEFIK DEFAULT CERT
```
