### ISSUE TITLE
Wrong units exposed by the IngressPerAppEndpoint

### ISSUE THREAD

**Issue by gboutry** [canonical/traefik-k8s-operator#260]
### Bug Description

After a scenario of scale up and scale down, traefik exposed only the missing unit.

### To Reproduce

1. deploy traefik and an application
2. scale up the application to 2 (wait for readiness)
3. scale down the application back to 1
4. Look at traefik routes

### Environment

Traefik: 1.0/candidate 148
Juju: 3.1.5-genericlinux-amd64
Juju agent: 3.1.5
Microk8s: MicroK8s v1.28.0 revision 5802
OS: Ubuntu 22.04.3 LTS
ingress.py: 2.6

###### Logs too long for github comments
Debug logs: https://pastebin.ubuntu.com/p/3JsfT9TGQp/
Traefik container logs: https://pastebin.ubuntu.com/p/ZVx2RK4XBR/

### Additional context

Show unit:
```yaml
  - relation-id: 15
    endpoint: ingress
    related-endpoint: ingress-public
    application-data:
      model: '"zaza-de71889d82db"'
      name: '"neutron"'
      port: "9696"
      redirect-https: "false"
      scheme: '"http"'
      strip-prefix: "false"
    related-units:
      neutron/0:
        in-scope: true
        data:
          host: '"neutron-0.neutron-endpoints.zaza-de71889d82db.svc.cluster.local"'
```

Traefik definition:
```yaml
# root@traefik-public-0:/opt/traefik/juju# cat juju_ingress_ingress_15_neutron.yaml 
http:
  routers:
    juju-zaza-de71889d82db-neutron-router:
      entryPoints:
      - web
      rule: PathPrefix()
      service: juju-zaza-de71889d82db-neutron-service
    juju-zaza-de71889d82db-neutron-router-tls:
      entryPoints:
      - websecure
      rule: PathPrefix()
      service: juju-zaza-de71889d82db-neutron-service
      tls:
        domains:
        - main: 10.20.20.3
          sans:
          - '*.10.20.20.3'
  services:
    juju-zaza-de71889d82db-neutron-service:
      loadBalancer:
        servers:
        - url: http://neutron-1.neutron-endpoints.zaza-de71889d82db.svc.cluster.local:9696
```

Servers url changed from having neutron-0 and neutron-1 to neutron-1 only, and after some time back to neutron-0 only.
