### ISSUE TITLE
TCP routes support (with TLS) 

### ISSUE THREAD

**Issue by shipperizer** [canonical/traefik-k8s-operator#276]
### Enhancement Proposal

Traefik supports TCP routes off the shelf, it would be good to get support in the charm via a new relation or the existing one

Extended documentation is available [here](https://doc.traefik.io/traefik/routing/routers/#general_2)

Brief example below:

```yaml
tcp:
  routers:
    glauth-router:
      rule: "HostSNI(`glauth.svc.cluster.local`)"
      service: glauth
      # will terminate the TLS request by default
      tls: {}
```

our use case is to support an application that natively doesn't do TCP over TLS, so we need something in front of it that allows that

this application is GLAuth, we are working on the charm but we are able to explain how to spin that up and use it for testing, GLAuth exposes an LDAP server (TCP protocol) and can be tested via `ldap*` cli tools
