### ISSUE TITLE
Traefik generates TLS config only for the first defined HTTP router

### ISSUE THREAD

**Issue by mmkay** [canonical/traefik-k8s-operator#352]
### Bug Description

In `_update_dynamic_config_route(...`, a TLS config is added to the HTTP routers created via TraefikRoute:
https://github.com/canonical/traefik-k8s-operator/blob/main/src/charm.py#L796

However, if there's more than one router defined in `http` section, it creates the config only for the first entry. It also doesn't create TLS entries for TCP routers.

### To Reproduce

- create a traefik-route relation that defines more than 1 http router (you can use `edge` [tempo-k8s-operator](https://github.com/canonical/tempo-k8s-operator) for that)
- look at generated traefik dynamic config in traefik's container:
- `juju ssh --container traefik traefik/0`

- see that a separate `{ROUTER_NAME}-tls` config is created only for the first http router, pointing at `websecure` entrypoint regardless of what entrypoint the original router points to:

```
root@traefik-0:/etc/traefik# cat /opt/traefik/juju/juju_ingress_traefik-route_49_tempo.yaml 
http:
  routers:
    juju-test-tls-tempo-jaeger-thrift-http:
      entryPoints:
      - jaeger-thrift-http
      rule: ClientIP(`0.0.0.0/0`)
      service: juju-test-tls-tempo-service-jaeger-thrift-http
    juju-test-tls-tempo-jaeger-thrift-http-tls:
      entryPoints:
      - websecure
      rule: ClientIP(`0.0.0.0/0`)
      service: juju-test-tls-tempo-service-jaeger-thrift-http
      tls: {}
    juju-test-tls-tempo-otlp-http:
      entryPoints:
      - otlp-http
      rule: ClientIP(`0.0.0.0/0`)
      service: juju-test-tls-tempo-service-otlp-http
    juju-test-tls-tempo-tempo-http:
      entryPoints:
      - tempo-http
      rule: ClientIP(`0.0.0.0/0`)
      service: juju-test-tls-tempo-service-tempo-http
    juju-test-tls-tempo-zipkin:
      entryPoints:
      - zipkin
      rule: ClientIP(`0.0.0.0/0`)
      service: juju-test-tls-tempo-service-zipkin
  services:
    juju-test-tls-tempo-service-jaeger-thrift-http:
      loadBalancer:
        servers:
        - url: http://tempo-0.tempo-endpoints.test-tls.svc.cluster.local:14268
    juju-test-tls-tempo-service-otlp-http:
      loadBalancer:
        servers:
        - url: http://tempo-0.tempo-endpoints.test-tls.svc.cluster.local:4318
    juju-test-tls-tempo-service-tempo-http:
      loadBalancer:
        servers:
        - url: http://tempo-0.tempo-endpoints.test-tls.svc.cluster.local:3200
    juju-test-tls-tempo-service-zipkin:
      loadBalancer:
        servers:
        - url: http://tempo-0.tempo-endpoints.test-tls.svc.cluster.local:9411
tcp:
  routers:
    juju-test-tls-tempo-otlp-grpc:
      entryPoints:
      - otlp-grpc
      rule: ClientIP(`0.0.0.0/0`)
      service: juju-test-tls-tempo-service-otlp-grpc
  services:
    juju-test-tls-tempo-service-otlp-grpc:
      loadBalancer:
        servers:
        - address: tempo-0.tempo-endpoints.test-tls.svc.cluster.local:4317
```

### Environment

`latest/edge` traefik

### Relevant log output

```shell
code already shows the problem
```
