### ISSUE TITLE
Skip tls config when passthrough is enabled

### ISSUE THREAD

**Issue by arturo-seijas** [canonical/traefik-k8s-operator#425]
### Bug Description

When creating a tcp route via the `submit_to_traefik` method in the charm lib, two routes are created instead of one and the second overrides the first. For instance:
```
juju-stg-wazuh-k8s-wazuh-server-enrole-tcp:
      entryPoints:
      - enrole-tcp
      rule: HostSNI(`*`)
      service: juju-stg-wazuh-k8s-wazuh-server-service-enrole-tcp
      tls:
        passthrough: true
```
results in
```
    juju-stg-wazuh-k8s-wazuh-server-enrole-tcp:
      entryPoints:
      - enrole-tcp
      rule: HostSNI(`*`)
      service: juju-stg-wazuh-k8s-wazuh-server-service-enrole-tcp
      tls:
        passthrough: true
    juju-stg-wazuh-k8s-wazuh-server-enrole-tcp-tls:
      entryPoints:
      - enrole-tcp
      rule: HostSNI(`*`)
      service: juju-stg-wazuh-k8s-wazuh-server-service-enrole-tcp
      tls: {}
```
being the second route name larger, it is matched, rendering the `tls` config useless.

### To Reproduce

Related a charm that configures traefik as follows https://github.com/canonical/wazuh-server-operator/blob/main/src/traefik_route_observer.py#L99
Probably simpler to code a failing test than actually reproduce with a Wazuh deployment, which requires several of components

### Environment

rev 194

### Relevant log output

```shell
None
```
