### ISSUE TITLE
Traefik appends a `tls` route even when `tls` routes are explicitly provided

### ISSUE THREAD

**Issue by IbraAoad** [canonical/traefik-k8s-operator#430]
Summarizing my understanding of what's going on here... please correct any mistakes

For every route, the previous code created a duplicate route `ROUTENAME-tls` for the same `rule` and `service` but with additional TLS configuration.  Both applied to the same `rule` and thus conflict, and the new `ROUTENAME-tls` route takes precedence over the original `ROUTENAME` because its name is longer.  Prior to canonical/traefik-k8s-operator#425 this worked fine because we wanted to use `ROUTENAME-tls` in all cases.

The updated code here avoids making the second `-tls` route in the specific case where the route includes `tls: passthrough: true`.

Have we really solved the broader problem here, or narrowly fixed canonical/traefik-k8s-operator#425?  Two questions come to mind:
1) are there other TLS configurations that someone might pass to traefik via `submit_to_traefik`?  If so, the same issue as canonical/traefik-k8s-operator#425 will occur
2) Should the charm be creating these duplicate routes that mask the original routes in the first place?  That might be out of scope for the fix here, but we should at least document it as an issue if it is actually an issue.

_Originally posted by @ca-scribner in https://github.com/canonical/traefik-k8s-operator/pull/429#discussion_r1863903261_

**Comment by IbraAoad** [comment]
This was first introduced as part of https://github.com/canonical/traefik-k8s-operator/pull/100, Trying on grafana which passes tls configs on its own gives the below results,

```
  routers:
    juju-trfk-test-grafana-k8s-router:
      entryPoints:
      - web
      middlewares:
      - juju-sidecar-noprefix-trfk-test-grafana-k8s
      - juju-sidecar-redir-https-trfk-test-grafana-k8s
      rule: PathPrefix(`/trfk-test-grafana-k8s`)
      service: juju-trfk-test-grafana-k8s-service
    juju-trfk-test-grafana-k8s-router-tls:
      entryPoints:
      - websecure
      rule: PathPrefix(`/trfk-test-grafana-k8s`)
      service: juju-trfk-test-grafana-k8s-service
      tls:
        domains:
        - main: foo.bar
          sans:
          - '*.foo.bar'
    juju-trfk-test-grafana-k8s-router-tls-tls:
      entryPoints:
      - websecure
      rule: PathPrefix(`/trfk-test-grafana-k8s`)
      service: juju-trfk-test-grafana-k8s-service
      tls:
        domains:
        - main: foo.bar
          sans:
          - '*.foo.bar'
```
the duplicate tls route is redundant in this case, yet we need to investigate if anything breaks on `plaintext` communication if the added tls route isn't there.
