### ISSUE TITLE
Traefik-route middlewares are not appended on tls

### ISSUE THREAD

**Issue by nsklikas** [canonical/traefik-k8s-operator#476]
### Bug Description

I am trying to use traefik-route to expose my app. This  is what I see in the databag:

```
$ juju show-unit traefik-public/0  --endpoint traefik-route
traefik-public/0:
  workload-version: v2.11.0
  opened-ports: []
  charm: ch:amd64/traefik-k8s-176
  leader: true
  life: alive
  relation-info:
  - relation-id: 23
    endpoint: traefik-route
    related-endpoint: ingress
    application-data:
      config: |
        http:
          middlewares:
            juju-sidecar-noprefix-test-user-verification-service:
              stripPrefix:
                forceSlash: false
                prefixes:
                - /test-user-verification-service
          routers:
            juju-test-user-verification-service-api-router:
              entryPoints:
              - web
              middlewares:
              - juju-sidecar-noprefix-test-user-verification-service
              rule: PathPrefix(`/test-user-verification-service/ui`)
              service: juju-test-user-verification-service-api-service
            juju-test-user-verification-service-api-router-tls:
              entryPoints:
              - websecure
              middlewares:
              - juju-sidecar-noprefix-test-user-verification-service
              rule: PathPrefix(`/test-user-verification-service/ui`)
              service: juju-test-user-verification-service-api-service
              tls:
                domains:
                - main: 10.64.140.44
                  sans:
                  - '*.10.64.140.44'
          services:
            juju-test-user-verification-service-api-service:
              loadBalancer:
                servers:
                - url: http://user-verification-service.test.svc.cluster.local:8080
...
```

BUT, this is the produced config:

```
root@traefik-public-0:/# cat /opt/traefik/juju/juju_ingress_traefik-route_23_user-verification-service.yaml 
http:
  middlewares:
    juju-sidecar-noprefix-test-user-verification-service:
      stripPrefix:
        forceSlash: false
        prefixes:
        - /test-user-verification-service
  routers:
    juju-test-user-verification-service-api-router:
      entryPoints:
      - web
      middlewares:
      - juju-sidecar-noprefix-test-user-verification-service
      rule: PathPrefix(`/test-user-verification-service/ui`)
      service: juju-test-user-verification-service-api-service
    juju-test-user-verification-service-api-router-tls:
      entryPoints:
      - websecure
      rule: PathPrefix(`/test-user-verification-service/ui`)
      service: juju-test-user-verification-service-api-service
      tls: {}
  services:
    juju-test-user-verification-service-api-service:
      loadBalancer:
        servers:
        - url: http://user-verification-service.test.svc.cluster.local:8080
```

I was informed that there is a `raw` flag that is supposed to stop this filtering, but it works only for `tcp` routers (see [here](https://github.com/canonical/traefik-k8s-operator/blob/main/src/charm.py#L968). Would you be open to applying the same logic for `http` routers as well? I can open a PR if you are fine with this.
