### ISSUE TITLE
Forward-auth support for traefik-route

### ISSUE THREAD

**Issue by natalian98** [canonical/traefik-k8s-operator#492]
### Enhancement Proposal

Right now the [forward-auth](https://github.com/canonical/traefik-k8s-operator/blob/ab2fd7ad4cf1a944f9c5b78cb7b89926eded3cf4/src/traefik.py#L553) middleware is added to routes generated by ingress-per-app, leader and unit:
```
middlewares:
    juju-sidecar-forward-auth:
      forwardAuth:
        address: https://oauth2-proxy-k8s.model.svc.cluster.local:4180
        authResponseHeaders:
        - X-Auth-User
        - <other headers>
```
To use it with traefik-route you need to add that config block yourself and pass the route to traefik. That requires third party charms to integrate with `forward-auth` interface in order to know the proxy address and headers.

Traefik-route already has a feature for appending tls middleware, perhaps it would make sense to add a similar flag to automatically add the forwardAuth middleware.
A point to consider is whether traefik should append the middleware to all routes as the purpose of the route relation is to adjust it to your charm's needs and you may want to exclude some paths from it. Another approach is to provide the proxy address as part of the `traefik_route` interface so that the extra relation is not needed.
