### ISSUE TITLE
certificate transfer is not working when related to some revisions of self-signed-certificates

### ISSUE THREAD

**Issue by ca-scribner** [canonical/traefik-k8s-operator#495]
### Bug Description

Traefik uses the `receive-ca-cert` relation (`certificate_transfer` interface) to add additional CA-certs to Traefik.  These are needed whenever downstream applications use TLS (eg: provide URLs with an `https` schema) with certificates that are not signed by a "well known" provider.  An example of how a user takes advantage of this is:

```
juju deploy traefik-k8s --trust
juju deploy self-signed-certificates
juju relate traefik-k8s:receive-ca-cert self-signed-certificates
```

Currently though if you do this with the latest traefik-k8s (r236) and self-signed-certificates (r308) charms, the ca-certs do not show up in traefik's local store (`/usr/local/share/ca-certificates` inside the Traefik container) even though they do show up in the relation data:
```
juju show-unit traefik/0                                   
traefik/0:
  charm: ch:amd64/traefik-k8s-236
  relation-info:
  ...   
  - relation-id: 10
    endpoint: receive-ca-cert
    related-endpoint: send-ca-cert
    application-data:
      certificates: '["-----BEGIN CERTIFICATE-----\nMIIDTTCCAj ... \n-----END CERTIFICATE-----"]'
      version: "1"
...
```

In traefik, we see this debug-log:
```
Provider relation data did not pass JSON Schema validation
```

which comes from [this validation error](https://github.com/canonical/traefik-k8s-operator/blob/ab2fd7ad4cf1a944f9c5b78cb7b89926eded3cf4/lib/charms/certificate_transfer_interface/v0/certificate_transfer.py#L392).  This is a result of **a mismatch between traefik's certificate-transfer lib (v0) and self-signed-certificates's certificate-transfer-lib (v1)**.  They both use the same interface name (`certificate_transfer`) but **v1 has a different schema than v0** as discussed [in this implementing pr](https://github.com/canonical/certificate-transfer-interface/pull/89).

### To Reproduce

See above

### Environment

.

### Relevant log output

.
